name: 'Validate JSON Schemas'
description: 'Find json files and validate them agains $schema'
branding:
    icon: 'check-circle'
    color: 'blue'
inputs:
    files:
        description: 'Files to validate'
        required: true
    schema:
        description: 'Schema location'
        required: false
    use-draft04:
        description: 'If the schema requires draft04 set this to trough'
        default: false
        required: false
    print-valid-files:
        description: 'Print valid file names to console'
        default: false
        required: false
runs:
    using: 'node12'
    main: 'dist/index.js'
